powerdata <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
powerdata$Date <- as.Date(powerdata$Date, format="%d/%m/%Y")
mydata <- subset(powerdata, Date == "2007-02-01" | Date == "2007-02-02")
mydata$Global_active_power <- as.character(mydata$Global_active_power)
mydata$Global_active_power <- as.numeric(mydata$Global_active_power)
mydata$datetime <- paste(as.character(mydata$Date), as.character(mydata$Time))
mydata$datetime <- strptime(mydata$datetime, format = "%Y-%m-%d %H:%M:%S")
with(mydata, plot(datetime, Global_active_power, type = "l", ylab = "Global Active Power (kilowatts)", xlab = ""))
dev.copy(png, "plot2.png")
dev.off()